//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilet
    {
        public int id { get; set; }
        public Nullable<int> guzergahid { get; set; }
        public string guzergahadi { get; set; }
        public Nullable<int> koltukno { get; set; }
        public Nullable<double> ucret { get; set; }
        public string kad { get; set; }
        public string ksoyad { get; set; }
    }
}
