//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guzergah
    {
        public int id { get; set; }
        public string guzergahad { get; set; }
        public Nullable<double> ucret { get; set; }
        public Nullable<int> bkoltuk { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public Nullable<int> zamsay { get; set; }
    }
}
